---
name: "¯\\_(ツ)_/¯ Something Else"
description: You simply have a question or something else? Submit them here!
title: "[Question]: "
labels: ["question", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        First of all thank you for discovering and submitting an issue.

        To increase the chance that someone may be able to help you
        please fill the form below as good as you can.

  - type: checkboxes
    id: todos
    attributes:
      label: To Dos
      description: Before submitting please confirm and check the following options.
      options:
        - label: I already searched with my favorite search engine "How to do X with rstcheck".
          required: true
        - label: I already read and followed the README and didn't find an answer.
          required: true
        - label: >
            I have checked the [issues](https://github.com/rstcheck/rstcheck/issues)
            and think that this is not a duplicate.
          required: true
        - label: I added a very descriptive title to this issue.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your question or issue.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true

  - type: textarea
    id: os-details
    attributes:
      label: Operating System Details
      description: >
        Optionally add more information about your operating system,
        especially if you choose "Other".

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: |
        What Python version(s) are you using?

        You can find the Python version with:

        ```shell
        python --version
        ```
    validations:
      required: true

  - type: input
    id: rstcheck-version
    attributes:
      label: rstcheck Version
      description: |
        What rstcheck & rstcheck-core versions are you using?

        You can find the versions with:

        ```shell
        rstcheck --version
        ```
    validations:
      required: true
